---
- hosts: rpigpstrackerdemo
  remote_user: pi
  sudo: yes
  tasks:
    - name: Make sure gpsd is installed
      apt: name=gpsd state=present
    - name: Make sure gpsd-clients is installed
      apt: name=gpsd state=present
    - name: Make sure python-gps is installed
      apt: name=gpsd state=present
    - name: update gpsd defaults
      copy: src=gpsd.settings dest=/etc/default/gpsd owner=root group=root mode=644 backup=yes
    - name: restart gpsd
      command: killall gpsd
      notify:
        - Restart gpsd

  handlers:
    - name: Restart gpsd
      command: gpsd /dev/ttyUSB0 -F /var/run/gpsd.sock
